SET foreign_key_checks=0;
DROP TABLE IF EXISTS `admin`;
DROP TABLE IF EXISTS `clockin`;
DROP TABLE IF EXISTS `contestregistion`;
DROP TABLE IF EXISTS `integral`;
DROP TABLE IF EXISTS `notice`;
DROP TABLE IF EXISTS `choice`;
DROP TABLE IF EXISTS `signon`;
DROP TABLE IF EXISTS `testinfo`;
DROP TABLE IF EXISTS `testrecord`;
DROP TABLE IF EXISTS `title`;
DROP TABLE IF EXISTS `titlediff`;
DROP TABLE IF EXISTS `userinfo`;
DROP TABLE IF EXISTS `wrongtitle`;
DROP TABLE IF EXISTS `contesttitle`;
DROP TABLE IF EXISTS `feedback`;
DROP TABLE IF EXISTS `testtitle`;
